# Generated by Django 3.0.7 on 2020-06-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
